apiVersion: apps/v1
kind: Deployment
metadata:
  name: tbfront
spec:
  selector:
    matchLabels:
      app: tbfront
  template:
    metadata:
      labels:
        app: tbfront
    spec:
      containers:
        - name: tbfront
          image: tbfront:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000